---
title: "WORKSHEET NO.3"
author: "JISIELLE MAE LAGO"
output: pdf_document
date: "2022-10-26"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

**Using Vectors**
1.	There is a built-in vector LETTERS contains the uppercase letters of the alphabet and letters which contains the lowercase letters of the alphabet.

 ```{}
 LETTERS	
##	[1] "A" "B" "C" "D" "E" "F" "G" "H" "I" "J" "K" "L" "M" "N" "O" 
"P" "Q" "R" "S" 
## [20] "T" "U" "V" "W" "X" "Y" "Z"
```
```{}
LETTERS <-c("A", "B", "C", "D", "E", "F" ,"G" ,"H","I","J" ,"K",
"L" ,"M" ,"N" ,"O", "P" ,"Q" ,"R", "S" ,"T", "U" ,"V", "W" ,"X","Y", "Z")
```

```{}
 letters	
##	[1] "a" "b" "c" "d" "e" "f" "g" "h" "i" "j" "k" 
"l" "m" "n" "o" "p" "q" "r" "s" 
## [20] "t" "u" "v" "w" "x" "y" "z"

```
```{}
letters <-c( "a","b" ,"c" ,"d" ,"e", "f","g" ,"h", "i" ,"j", "k",
"l" ,"m" ,"n" ,"o" ,"p","q" ,"r", "s","t" ,"u","v", "w" ,"x" ,"y" ,"z")
```


**Based on the above vector LETTERS:**

a.	You need to produce a vector that contains the first 11 letters.
```{}

LETTERS[1:11]
 [1] "A" "B" "C" "D" "E" "F" "G" "H" "I" "J" "K"

```

b.	Produce a vector that contains the odd numbered letters.\

```{}
LETTERS[1:26 %% 2 != 0]
 [1] "A" "C" "E" "G" "I" "K" "M" "O" "Q" "S" "U" "W" "Y"

```

c.	Produce a vector that contains the vowels
```{}
vow1 <-LETTERS[c(1,5,9,15,21)]
vow1
[1] "A" "E" "I" "O" "U"

```

Based on the above vector letters:

```{}
d.	Produce a vector that contains the last 5 lowercase letters.

letters[-(1:21)]
[1] "v" "w" "x" "y" "z"

```

e.	Produce a vector that contains letters between 15 to 24 letters in lowercase.
```{}

letters[15:24]
 [1] "o" "p" "q" "r" "s" "t" "u" "v" "w" "x"
 
```



2.	Create a vector with the average temperatures in April for Tuguegarao City, Manila, Iloilo City, Tacloban, Samal Island, and Davao City. The average temperatures in Celcius are 42, 39, 34, 34, 30, and 27 degrees.

```{}

a.	What is the R code and its result for creating a character vector 
for the city/town of Tuguegarao City, Manila, Iloilo City, Tacloban, Samal Island, and Davao City? 
Name the object as city.The names should follow the same order as in the instruction.

```


```{}
city <-c("Tuguegarao City", "Manila", "Iloilo City", "Tacloban", "Samal Island","Davao City)

city
[1] "Tuguegarao City" "Manila"          "Iloilo City"    
[4] "Tacloban"        "Samal Island"    "Davao City"  


```


b.	The average temperatures in Celcius are 42, 39, 34, 34, 30, and 27 degrees. Name the object as temp. Write the R code and its output. Numbers should also follow what is in the instruction.

```{}
temp <-c(42, 39, 34, 34, 30,27 )
temp
[1] 42 39 34 34 30 27

```
c.	Associate the temperature temp with the city by using names() function. What is the R code and its result?

```{}
names(temp)<-city
temp
Tuguegarao City          Manila     Iloilo City        Tacloban 
             42              39              34              34 
   Samal Island      Davao City 
             30              27 


```

e. From the answer in d, what is the content of index 5 and index 6? What is its R code?

```{}
temp[5:6]
Samal Island   Davao City 
          30           27 
      
```
 
**Using Matrices**


```{}
•	Matrix can be created by specifying the rows and columns.
# row = 2
 matrix(c(5,6,7,4,3,2,1,2,3,7,8,9),nrow =2)	
##	[,1] [,2] [,3] [,4] [,5] [,6]
## [1,]	5	7	3	1	3	8
## [2,]	6	4	2	2	7	9
# row = 3 and column = 2
 matrix(data =c(3,4,5,6,7,8),3,2)	
##	[,1] [,2]
## [1,]	3	6
## [2,]	4	7
## [3,]	5	8

##	[,1] [,2] [,3] [,4] [,5]
## [1,]	1	0	0	0	0


 diag(6)		 ##	[,1] [,2] [,3] [,4] [,5] [,6]\
## [1,]	1	0	0	0	0	0
## [2,]	0	1	0	0	0	0
## [3,]	0	0	1	0	0	0
## [4,]	0	0	0	1	0	0
## [5,]	0	0	0	0	1	0
## [6,]	0	0	0	0	0	1

```

2.	Create a matrix of one to eight and eleven to fourteen with four columns and three rows.
```{}
a.	What will be the R code for the #2 question and its result?

n1<-matrix(data = c(1,2,3,4,5,6,7,8,11,12,13,14),3,4)\
n1
     [,1] [,2] [,3] [,4]
[1,]    1    4    7   12
[2,]    2    5    8   13
[3,]    3    6   11   14


```


b.	Multiply the matrix by two. What is its R code and its result?
```{}
n2<-matrix(data= rep(n1 * 2),3,4)
       n2
     [,1] [,2] [,3] [,4]
[1,]    2    8   14   24
[2,]    4   10   16   26
[3,]    6   12   22   28

```

c.	What is the content of row 2? What is its R code?
```{}
n1[2,]
[1]  2  5  8 13

```

d.	What will be the R code if you want to display the column 3 and column 4 in row 1 and row 2? What is its output?
```{}
n1[1:2,3:4]
     [,1] [,2]
[1,]    7   12
[2,]    8   13

```
e.	What is the R code is you want to display only the columns in 2 and 3, row 3? What is its output?
```{}

n1[3, 2:3]
[1]  6 11

```

f.	What is the R code is you want to display only the columns 4? What is its output?
```{}

n1[,4]
[1] 12 13 14

```

g.	Name the rows as isa, dalawa, tatlo and columns as uno, dos, tres, quatro
for the matrix that was created in b.‘. What is its R code and corresponding output?

```{}
dimnames(n1) <-list(c("isa","dalawa","tatlo"),c("uno","dos", "tres","quatro"))
 n1
 
       uno dos tres quatro
isa      1   4    7     12
dalawa   2   5    8     13
tatlo    3   6   11     14
 
 ```
 
h.	From the original matrix you have created in a, reshape the matrix by assigning a new dimension with dim(). New dimensions should have 2 columns and 6 rows. What will be the R code and its output?

```{}
dim(n1) <-c(6,2)
n1
     [,1] [,2]
[1,]    1    7
[2,]    2    8
[3,]    3   11
[4,]    4   12
[5,]    5   13
[6,]    6   14

```

**Using Arrays**

•	Array can have more than two dimensions by using the array() function and dim() to specify the dimensions
```{}

## , , 1 ##
##	[,1] [,2]	[,3]	[,4]
##	[1,]	1	4	7	10
##	[2,]	2	5	8	11
##	[3,]	3	6	9	12
##
## , , 2 ##
##	[,1] [,2]	[,3]	[,4]
##	[1,]	13	16	19	22
##	[2,]	14	17	20	23
##	[3,]	15	18	21	24

 
## [1] 3 4 2

## [1] 24
 
•	Another way to create arrays\

## , , 1 ##
##	[,1] [,2]	[,3]	[,4]
##	[1,]	1	4	7	10
##	[2,]	2	5	8	11
##	[3,]	3	6	9	12
##
## , , 2 ##
##	[,1] [,2]	[,3]	[,4]
##	[1,]	13	16	19	22
##	[2,]	14	17	20	23
##	[3,]	15	18	21	24

```

3.An array contains 1, 2, 3, 6, 7, 8, 9, 0, 3, 4, 5, 1
```{}
arr1<-c(1, 2, 3, 6, 7, 8, 9, 0, 3, 4, 5, 1)
 arr1
 [1] 1 2 3 6 7 8 9 0 3 4 5 1

```

a.	Create an array for the above numeric values. Each values will be repeated twice What will be the R code if you are to create a three-dimensional array with 4 columns and 2 rows. What will be its output?
```{}

n1_arr <-array(rep(arr1,2),dim = c(2,4,3))
n1_arr
, , 1

     [,1] [,2] [,3] [,4]
[1,]    1    3    7    9
[2,]    2    6    8    0

, , 2

     [,1] [,2] [,3] [,4]
[1,]    3    5    1    3
[2,]    4    1    2    6

, , 3

     [,1] [,2] [,3] [,4]
[1,]    7    9    3    5
[2,]    8    0    4    1

```

b.	How many dimensions do your array have?
```{}
3 dimensions 
```

c.	Name the rows as lowercase letters and columns as uppercase letters starting from the A. The array names should be “1st-Dimensional Array”, 
“2nd-Dimentional Array”, and “3rd-Dimensional Array”. 
What will be the R codes and its output?
```{}

dimnames(n1_arr) <-list (letters[1:2], LETTERS[1:4],c("1st-Dimensional Array",  "2nd-Dimentional Array", "3rd-Dimensional Array"))

 n1_arr   
, , 1st-Dimensional Array

  A B C D
a 1 3 7 9
b 2 6 8 0

, , 2nd-Dimentional Array

  A B C D
a 3 5 1 3
b 4 1 2 6

, , 3rd-Dimensional Array

  A B C D
a 7 9 3 5
b 8 0 4 1

```
